from pathlib import Path

SIMULATIONS = "simulations"
SAMPLES = "samples"
WIDTH = 'width'
JSON_FILE = Path("data.json")
current_dict = None 
LOWER_BOUND = 1
UPPER_BOUND = 1000000
SIM_PATH = "simulation/data"
RESULTS_PATH = "results"
SIM_GENOM_PATH = SIM_PATH + "/genome"
USER="amir"
GENOME_EXE = f'/mnt/data/{USER}/GWANN_PROJECT/genome-0.2-Linux/genome'
MODE = True
CUBLAS_WORKSPACE_CONFIG = ":16:8"
CPU = "cpu"
CUDA = "cuda:0" 
SEED = 0
PLOT_AVERAGE = False 
MOMENTUM = 0.9
LR = 1e-2  # learning rate 
WEIGHT_DECAY = 1e-5
MODELS_DIR = "models"
CLIP_GRAD_NORM = 5 
GAMMA= 0.8
TOTAL_METRICS = 4
INPUT = 'input'
OUTPUT = 'output'
POPULATION = 'population'
PLOT_SIZE = 2
MODEL_PATH_ACCURACY = "models/net-accuracy.pt"
MODEL_PATH_MIN_LOSS = "models/net.pt"
MODEL_PATH_TENSOR_DIR = './models'
LOGGER_DIR = 'logs'
VCF_DATA_DIR = 'vcf_data'